### PR TITLE
Courtney

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by clburns107** [comment]
Tables are done

https://docs.google.com/spreadsheets/d/1YyyP3o9wWL9AKa0nACEdBlhm2vw4LlAdOM3IEd3rU1E/edit?usp=sharing

**Comment by sumeetjain** [comment]
:+1:

**Comment by clburns107** [comment]
Im confused on what kind of datatype an id referencing another table would be.  Would that be an integer since it's technically a number?

**Comment by sumeetjain** [comment]
Yup!

**Comment by clburns107** [comment]
getting error when trying to define my table columns that reference other columns as integers.  When i use quotes i get this error

Error: You need to indicate a valid data type for the column you're adding.
For example, `DB.define_column('users', 'name', 'string')`.
The valid data types are: binary, boolean, date, datetime, decimal, float, integer, primary_key, references, string, text, time, timestamp

If I dont use quotes i get this error /Users/mac/Code/web-app__swimming-competition/db/define_schema.rb:18:in `<top (required)>': undefined local variable or method`integer' for main:Object (NameError)
Did you mean?  Integer

if i capitalize it i just get the first error again.

**Comment by sumeetjain** [comment]
Can you please commit your code? I'd like to see the broken code, so that I can help debug it.

**Comment by sumeetjain** [comment]
- [ ] `DB.define_column("conferences","region")` looks like the problem line. It's not giving a datatype at all.
- [ ] `'Integer'` should be `'integer'`.
- [ ] `DB.define_column("events", "stroke",string')` should be `DB.define_column("events", "stroke", 'string')`

**Comment by clburns107** [comment]
im confused as to when to use singular quotes vs. double. does it matter?

**Comment by sumeetjain** [comment]
> does it matter?

Rarely.

``` ruby
x = "Hello!"
# same as
x = 'Hello!'

x = "Hi, #{@name}!" # Works
x = 'Hi, #{@name}!' # Does not work
```

There are a couple other cases, but generally speaking you can use either. I suggest sticking with doubles only–makes life easier.

**Comment by clburns107** [comment]
getting another error now it looks as though is in sinatra?

/Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1595:in `define_method': tried to create Proc object without a block (ArgumentError)
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1595:in`generate_method'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1604:in `compile!'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1583:in`route'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.6/lib/sinatra/base.rb:1370:in `get'
    from /Users/mac/Code/web-app__swimming-competition/app/controllers/main_controller.rb:17:in`<top (required)>'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in`require_with_backports'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in`load_dependency'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
    from /Users/mac/Code/web-app__swimming-competition/main.rb:51:in`block in <top (required)>'
    from /Users/mac/Code/web-app__swimming-competition/main.rb:51:in `each'
    from /Users/mac/Code/web-app__swimming-competition/main.rb:51:in`<top (required)>'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/mac/Code/web-app__swimming-competition/config.ru:1:in `block in <main>'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in`instance_eval'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
    from /Users/mac/Code/web-app__swimming-competition/config.ru:in`new'
    from /Users/mac/Code/web-app__swimming-competition/config.ru:in `<main>'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in`eval'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in`parse_file'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:208:in`app'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:272:in`start'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
    from /Users/mac/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/bin/rackup:4:in`<top (required)>'
    from /Users/mac/.rbenv/versions/2.3.0/bin/rackup:23:in `load'
    from /Users/mac/.rbenv/versions/2.3.0/bin/rackup:23:in`<main>'

**Comment by clburns107** [comment]
two controllers and view files complete with form. I want to make sure im doing this right... i have lots of questions.

**Comment by sumeetjain** [comment]
I think you might need to clarify your question for me–might be a wording issue. You're asking about "displaying every object in a column". Can you give me an example of what this "column" might be/contain? And what one "object" in it would be?

**Comment by clburns107** [comment]
Yes. So i have a table called regions. In the table is a column called city.  After the users adds a new city to the table and it saves the next page that loads is a "Success!" page.  I would like that Success page to display a list of all the current cities in the table.  kinda like a "heres what we have so far" page.

**Comment by sumeetjain** [comment]
Gotcha. That sounds good. When we talk about _objects_ with ActiveRecord, usually we are referring to the entire row.

This means that, on the Success page, you want to display a certain _property_ (the 'city') of each _row_ in the `regions` table.

When you do `Region.all`, you get back a list (an `Array`) of _all rows_ from the `regions` table. Each row is represented by an _object_. Each object has _properties_ like 'id' and 'city'.

In your Success page's controller action, store `@regions = Region.all`. Then in the view for that action, loop through `@regions` and decorate each set of information using HTML.

So let's say `@regions` is this:

``` ruby
[
  R1,
  R2,
  R3,
  R4
]
```

That's an Array with "Region objects" in it (I'm using R1, etc to represent an object).

With this loop...

``` erb
<% @regions.each do |x| %>
```

...you can access each object with `x`. Like `x.city`.

So you might have something like `<%= x.city %>` inside of that loop.

Let me know if this helps you move forward. I'm happy to come over and work together a bit.

**Comment by clburns107** [comment]
if you could walk me through it in person i might be able to understand a bit better.

**Comment by sumeetjain** [comment]
You bet! On my way.

**Comment by sumeetjain** [comment]
Looks perfect, best I can tell. :+1:

**Comment by clburns107** [comment]
I ran into this last night. For some reason... my table wont display and im pretty much just copying code. Unless its something minuscule i cant see.. I dont remember how i fixed it last night.

**Comment by clburns107** [comment]
I need help with this code.  Im not sure if my "fake array" is supposed to run or not? It currently does not. My code is dependent on the params that are entered for the page.

**Comment by halfghaninne** [comment]
What is [this method](https://github.com/clburns107/web-app__swimming-competition/blob/459d459a1de96ad1e51557b9543ee03e9c3aba67/app/models/competition.rb#L3-L5) returning?

Check by putting a binding.pry between [these lines](https://github.com/clburns107/web-app__swimming-competition/blob/459d459a1de96ad1e51557b9543ee03e9c3aba67/app/controllers/view_all_controllers.rb#L27-L28)

**Comment by clburns107** [comment]
that method is running on the erb page... should i have the binding.pry after the erb is path is defined by the controller?

**Comment by clburns107** [comment]
binding.pry doesnt show my method when put on line 28

**Comment by clburns107** [comment]
I wrote a method called .city to capture the city for each contestant.  When using the .city method in a loop i expected to see the contestants city displayed. Instead, calling the city method on the variable returns the word "Region" for every entry.  Im not sure why because "Region" isnt even an entry as data inside the Regions table. .... oh boy...

**Comment by halfghaninne** [comment]
I see that [you're calling](https://github.com/clburns107/web-app__swimming-competition/blob/ee8fdb72231e5b778d9319e134eb3d44ca7bd365/app/models/contestant.rb#L4) `.name` on the Region Object.

Your [schema shows](https://github.com/clburns107/web-app__swimming-competition/blob/ee8fdb72231e5b778d9319e134eb3d44ca7bd365/db/define_schema.rb#L25) Region Objects having the column `city`. Does calling `.city` [here](https://github.com/clburns107/web-app__swimming-competition/blob/ee8fdb72231e5b778d9319e134eb3d44ca7bd365/app/models/contestant.rb#L4) instead help?

**Comment by clburns107** [comment]
I have updated my variable to call .city. I expected to see the name value of city for the object but instead im getting a no method error. This perplexes me since I thought that i could call any column name on an object as a method.

**Comment by clburns107** [comment]
Im trying to add my method to capture the city for each contestant to on my category info page.  I know the loop will work to display  by column name for each object so i expected it to go grab the city name when i added my method to it.  However it get a no method error.

**Comment by clburns107** [comment]
Please help with last commit message.

**Comment by clburns107** [comment]
I have a collection of result objects (@all_scores).  It doesnt like it if i do @all_scores.order_scores

**Comment by halfghaninne** [comment]
Yep. `@all_scores` is a collection, and you've written `.order_scores` to be called on an individual instance.

You could consider changing `.order_scores` to be a [Class Method](http://culttt.com/2015/06/10/understanding-class-methods-verses-instance-methods-in-ruby/).

**Comment by clburns107** [comment]
please see last commit comment

**Pull request closed without merging**
